spring.application.name=pflegedoku-backend
# Spring AI / Ollama Einstellungen
# spring.ai.ollama.base-url=http://localhost:11434
# spring.ai.ollama.chat.options.model=llama3
# spring.ai.ollama.chat.options.temperature=0.1
# spring.ai.ollama.chat.options.num-predict=2048

# 1. Laedt die .env-Datei aus dem Root-Verzeichnis
spring.config.import=optional:file:.env[.properties]

# 2. OpenAI Konfiguration
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0.0

# JWT CONFIG
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS}